#!/usr/bin/env bash
#copied number 2, and then inserting a case select for the special cases taht'll apply afterward. if it's anything liek if, it'll need to be listed as occuring after the reelvant interval, at hte beginning of one interval too late for it to happen at the right time

numberAboutToBeDone=1
while [ $numberAboutToBeDone -le 20 ]
do
    echo "$numberAboutToBeDone"
    ((numberAboutToBeDone++))
    case $numberAboutToBeDone in
	5) echo "bad luck from China" ;;
        10) echo "bad luck from Japan" ;;
        18) echo "bad luck from Italy" ;;
    esac
    
done
